# Generated by Django 5.2 on 2025-06-21 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0004_remove_user_has_ev_access_remove_user_has_sv_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=256, null=True)),
                ('session_id', models.CharField(blank=True, max_length=512, null=True)),
                ('payment_intent_id', models.CharField(blank=True, max_length=512, null=True)),
                ('status', models.CharField(blank=True, max_length=256, null=True)),
                ('payment_status', models.CharField(blank=True, max_length=256, null=True)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('session_created_at', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth_app.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
