# Generated by Django 5.2 on 2025-06-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='notify_admin',
            field=models.BooleanField(default=False, help_text='Send notification to admin when user subscribes'),
        ),
    ]
