# Generated by Django 5.2 on 2025-06-10 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0002_subscriber_notify_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Guide Sub', 'verbose_name_plural': 'Guide Subs'},
        ),
    ]
