# Generated by Django 5.2 on 2025-06-15 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriber', '0003_alter_subscriber_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ['-subscribed_at'], 'verbose_name': 'Guide Sub', 'verbose_name_plural': 'List of Subscribers'},
        ),
    ]
