# Generated by Django 5.2 on 2025-06-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coaching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachinginfo',
            name='notify_admin',
            field=models.BooleanField(default=True, help_text='Notify admin by email when this form is submitted?'),
        ),
    ]
