# Generated by Django 5.2 on 2025-06-10 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coaching', '0002_coachinginfo_notify_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachinginfo',
            name='notify_admin',
        ),
    ]
