# Generated by Django 5.2 on 2025-06-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_notificationsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_ev_access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='has_sv_access',
        ),
    ]
