# Generated by Django 5.2 on 2025-05-07 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('writer_name', models.CharField(blank=True, help_text="Writer's name if not linked to a user", max_length=100)),
                ('category', models.CharField(choices=[('business', 'Business'), ('wellness', 'Wellness and Health'), ('travel', 'Travel'), ('personal', 'Personal Development')], default='business', max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_images/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='blog_blogpo_created_2e77d7_idx'), models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'), models.Index(fields=['status', '-created_at'], name='blog_blogpo_status_8774cb_idx'), models.Index(fields=['category'], name='blog_blogpo_categor_481d67_idx')],
            },
        ),
    ]
